// packages/solid/demo/src/App.tsx
import { Component, createEffect } from 'solid-js';
import { createDraggable } from '@neodrag/solid';

const App: Component = () => {
	let draggableRef: HTMLDivElement | undefined = undefined;

	const { dragState, isDragging } = createDraggable(
		() => draggableRef,
		() => ({ onDrag: () => console.log('Muhahahahahah') })
	);

	createEffect(() => {
		console.log({ isDragging: isDragging(), dragState: dragState() });
	});

	return <div ref={draggableRef}>Hello</div>;
};

export default App;

// packages/react/demo/src/App.tsx
import { useDraggable } from '@neodrag/react';
import { useEffect, useRef } from 'react';

function App() {
	const draggableRef = useRef<HTMLDivElement>(null);
	const { dragState, isDragging } = useDraggable<HTMLDivElement>(draggableRef, {
		onDrag: () => console.log('Muhahahahahah'),
	});

	useEffect(() => {
		console.log({ isDragging, dragState });
	}, [dragState, isDragging]);

	return <div ref={draggableRef}>Hello</div>;
}

export default App;
