// playground/vue/src/App.vue
<script setup lang="ts">
import { events, position, vDraggable } from '@neodrag/vue';
import { ref } from 'vue';

const pos = ref({ x: 0, y: 0 });
</script>

<template>
	<div
		class="box"
		v-draggable="
			() => [
				position({ current: pos }),
				events({
					onDrag: ({ offset }) => {
						pos.x = offset.x;
						pos.y = offset.y;
					},
				}),
			]
		"
	></div>

	<br /><br />

	X:
	<input type="range" min="0" max="300" :value="pos.x" @input="(e) => (pos.x = +e.target.value)" />
	Y:
	<input type="range" min="0" max="300" :value="pos.y" @input="(e) => (pos.y = +e.target.value)" />
</template>

<style scoped>
.box {
	height: 100px;
	width: 100px;
	background-color: cyan;
}
</style>

// playground/react/src/App.tsx
import { events, position as position_plugin, useDraggable } from '@neodrag/react';
import { useRef, useState } from 'react';

function App() {
	const [position, setPosition] = useState({ x: 0, y: 0 });
	const draggable_ref = useRef<HTMLDivElement>(null);

	useDraggable(draggable_ref, () => [
		position_plugin({ current: position }),
		events({
			onDrag: ({ offset }) => {
				setPosition({ x: offset.x, y: offset.y });
			},
		}),
	]);

	return (
		<>
			<div ref={draggable_ref}>I can be moved with the slider too</div>
			X:
			<input
				type="range"
				min="0"
				max="300"
				value={position.x}
				onInput={(e) =>
					setPosition((prev) => ({ ...prev, x: +(e.target as HTMLInputElement).value }))
				}
			/>
			Y:
			<input
				type="range"
				min="0"
				max="300"
				value={position.y}
				onInput={(e) =>
					setPosition((prev) => ({ ...prev, y: +(e.target as HTMLInputElement).value }))
				}
			/>
		</>
	);
}

export default App;
